namespace ClrScope.Mcp.Contracts;

public enum ClrScopeError
{
    // Validation errors (VALIDATION_* prefix)
    VALIDATION_INVALID_PID,
    VALIDATION_INVALID_DURATION,
    VALIDATION_INVALID_PROFILE,
    VALIDATION_MISSING_REQUIRED_FIELD,

    // Preflight errors (PREFLIGHT_* prefix)
    PREFLIGHT_PROCESS_NOT_FOUND,
    PREFLIGHT_NOT_DOTNET,
    PREFLIGHT_ARTIFACT_ROOT_NOT_WRITABLE,
    PREFLIGHT_DISK_SPACE_LOW,

    // Runtime errors (RUNTIME_* prefix)
    RUNTIME_PROCESS_EXITED,
    RUNTIME_ATTACH_FAILED,
    RUNTIME_COLLECTION_FAILED,
    RUNTIME_CANCELLATION_FAILED,

    // Storage errors (STORAGE_* prefix)
    STORAGE_SESSION_NOT_FOUND,
    STORAGE_ARTIFACT_NOT_FOUND,
    STORAGE_DATABASE_ERROR,
    STORAGE_FILE_IO_ERROR
}
